### GET all card api
GET http://localhost:3000/api/card

### GET get one card api
GET http://localhost:3000/api/card/2

### POST card api
POST http://localhost:3000/api/card HTTP/1.1
Content-Type: application/json

{
    "author": "user1", 
    "content": "페이지네이션 UI 리서치",
    "category": "해야할 일"
}

### PUT card api
PUT  http://localhost:3000/api/card/2 HTTP/1.1
Content-Type: application/json

{
    "author": "user2", 
    "content": "페이지네이션 UI 리서치, 다른 일... 추가",
    "category": "해야할 일"
}

### DELETE card api
DELETE http://localhost:3000/api/card/4

### GET all activity api
GET http://localhost:3000/api/activity

### POST activity api
POST http://localhost:3000/api/activity HTTP/2.0
Content-Type: application/json

{
    "userid": "1",
    "content": "updated 데모 환경 설정"
}