PATCH http://localhost:3000/api/card/10
Content-Type: application/json

{
    "data": {
        "prevColumn": "하는 중",
        "nextColumn": "다 했어",
        "orderInPrevColumn": 3,
        "orderInNextColumn": 2
    }
}

### GET column api
GET http://localhost:3000/api/column


### PUT column api
PUT http://localhost:3000/api/column/3
Content-Type: application/json

{
    "username": "Jason",
    "column_name": "다 했어요"
}