USE todo;

CREATE TABLE IF NOT EXISTS Cards (
	id BIGINT NOT NULL AUTO_INCREMENT,
	author VARCHAR(255) NOT NULL,
	last_updated TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	content TEXT NOT NULL,
	category VARCHAR(255) NOT NULL,
	PRIMARY KEY(ID)
	) ENGINE=InnoDB;
